version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: dsr-ng-dev
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx/back/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/back/dsr.dev.conf/:/etc/nginx/conf.d/default.conf
      - ./backend-static:/backend-static
      - ./media:/media
    depends_on:
      - back

  front:
    container_name: dsr-front-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    container_name: dsr-back-dev
    build:
      context: ./aidisraeli_backend
      dockerfile: Dockerfile
    command: sh -c "
      pipenv run python manage.py collectstatic --noinput
      && pipenv run python manage.py migrate
      && pipenv run gunicorn aidisraeli_proj.asgi:application -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker"
    image: back-image
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
      - POSTGRES_PORT=${POSTGRES_PORT_DOCKER}
    ports:
      - "8081:8000"
    volumes:
      - ./backend-static:/code/static
      - ./media:/code/media
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    container_name: dsr-db-dev
    volumes:
      - postgres_data_dsr:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

volumes:
  postgres_data_dsr:

