import {SITE_LANG_OPTIONS} from '../store/appGlobal/types';

export const EN = {
  translation: {
    mainHeader: {
      upgradeTariffToPro: 'Upgrade to Pro',
      proTariff: 'Pro plan',
      teamsTariff: 'Teams plan',
    },
    landing: {
      header: {
        main: 'Home',
        tariffs: 'Tariffs',
        contactUs: 'Contact',
        blog: 'Blog',
        login: 'Log in',
        registration: 'Register',
        profile: 'Profile',
      },
      main: {
        heading: 'Artificial Intelligence\nthat writes any\ntext for you',
        contentText:
          'Create quality blog posts,\nSEO articles, news, press releases\nand more in seconds',
        try4FreeButtonTitle: 'Try for free',
        contentSecondaryText: 'Nearly 100,000 authors\nare using Ai Copywriter',
      },
      whatCanBeCreatedBlock: {
        headingText: 'What can you create\nwith AI DISRAELI',
        gridTile1HeadingText: 'Advertising offers',
        gridTile1ListItemText1: 'Facebook Ads',
        gridTile1ListItemText2: 'Google Ads',
        gridTile1ListItemText3: 'Linkedin Ads',
        gridTile2HeadingText: 'Social\nMedia Content',
        gridTile2ListItemText1: 'Headlines',
        gridTile2ListItemText2: 'Instagram posts',
        gridTile2ListItemText3: 'Social media posts',
        gridTile3HeadingText: 'Text content\nfor the site',
        gridTile3ListItemText1: 'SEO articles',
        gridTile3ListItemText2: 'Subheadings',
        gridTile3ListItemText3: 'Meta Descriptions',
        gridTile4HeadingText: 'Commercial\ntexts',
        gridTile4ListItemText1: 'Product Descriptions',
        gridTile4ListItemText2: 'Product Benefits',
        gridTile4ListItemText3: 'Microcopies',
        gridTile5HeadingText: 'Content\nfor blogs',
        gridTile5ListItemText1: 'Headlines, ideas, blog outlines',
        gridTile5ListItemText2: 'Blog intro',
        gridTile5ListItemText3: 'Articles for the blog',
        gridTile6HeadingText: 'Selling/Intexts',
        gridTile6ListItemText1: 'Selling Text',
        gridTile6ListItemText2: 'Giving a marketing touch',
        gridTile6ListItemText3: 'AIDA Principle Texts',
      },
      howItWorks: {
        heading: 'How does it work?',
        lead: 'AI Disraeli allows you to use artificial intelligence\nto reduce your copywriting costs and increase your\nwriting speed and text count',
        step1: 'Choose the type of generation',
        step2: 'Enter basic information to generate',
        step3: 'Get your results and edit if necessary',
        whatCanHeading: 'What can\nAI DISRAELI do?',
        whatCan1: 'Rewrite text - new text with the meaning intact',
        whatCan2: 'Reduce the text to its essence',
        whatCan3: 'Write a text on a given topic',
        whatCan4: 'Create a text with the necessary emotional connotation',
        whatCanAdditional: '10 text options at each generation!',
      },
      footer: {
        main: 'Home',
        tariffs: 'Tariffs',
        contactUs: 'Contact',
        blog: 'Blog',
        profile: 'Personal profile',
        privacyPolicy: 'Privacy Policy',
        allRightsAreProtected: 'All Rights Reserved',
      },
      targetAudience: {
        heading: 'Who is the AI DISRAELI suitable for?',
        copywritersCardHeader: 'Copywriters',
        copywritersCardText:
          'Write unique articles with just one click using artificial intelligence tools for copywriting',
        studentsCardHeader: 'Students',
        studentsCardText: 'Create original student papers and high-quality essays in seconds',
        SEOCardHeader: 'SEO specialists',
        SEOCardText:
          'Agloritm for SEO articles can create genuinely human quality content that satisfies search engines',
        journalistsCardHeader: 'journalists',
        journalistsCardText:
          'Impress your readers and automatically create a first draft of your story',
        bloggersCardHeader: 'Bloggers',
        bloggersCardText:
          'Your personal blog post generator with artificial intelligence creates the perfect content for any niche',
        marketersCardHeader: 'Marketers',
        marketersCardText: 'Automate your content marketing tasks with AI software for copywriter',
        onlineShopsCardHeader: 'Online stores',
        onlineShopsCardText:
          'Create a variety of text options for your promotional offers and generate unique articles to test the site',
        devsCardHeader: 'Developers',
        devsCardText:
          'Get your own artificial intelligence-based tool and create content 10 times faster',
        tryForFreeButtonText: 'try for free',
      },
    },
    blog: {
      pageHeadingText: 'Blog',
      viewsNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'views;views',
      },
      continueReadingButtonText: 'Read more',
    },
    tariffs: {
      heading: 'Tariffs',
      lead: 'Save up to 15% with one of our annual plans',
      monthly: 'MONTHLY',
      yearly: 'ANNUAL',
      personal: 'Personal',
      forBusiness: 'For Business',
      forFree: 'Free',
      perMonth: 'month',
      perYear: 'month if you pay for a year',
      atMonth: 'per month',
      atFirstMonth: 'the first month',
      antiPlagiarism: 'Anti-plagiarism',
      perGeneration: 'per generation',
      tryForFree: 'Try',
      selectPlan: 'Select Plan',
      requestPrice: 'Submit a request',
      introTariffDescription: 'Perfect for getting to know the service',
      liteTariffDescription: 'For those with few tasks',
      starterTariffDescription: 'For those who are just planning to start',
      proTariffDescription: 'For professionals who value their time',
      teamTariffDescription: 'For teams who value collaboration',
      apiTariffDescription: 'For businesses that want to build functionality into their products',
      popularLabel: 'Popular',
      unlimitedAntiPlagiarism: 'Unlimited Anti-plagiarism',
      unlimitedProjects: 'Unlimited Projects',
      unlimitedWorkspaces: 'Unlimited Spaces',
      collaborateOnFilesAndProjects: 'Collaborate on files and projects',
      individualCPA: 'Individual CPA',
      personalAPI: 'Personal API',
      creditsPerMonthNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'credit;credits',
      },
      languagesNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'language;languages',
      },
      initialBonusCreditsNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'bonus credit;bonus credits',
      },
      antiPlagiarismChecksNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'check;checks',
      },
      maxProjectsNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'project;projects',
      },
      maxWorkspacesNumeralDependentForms: {
        language: SITE_LANG_OPTIONS.EN,
        wordForms: 'workspace;workspaces',
      },
      modal: {
        month: 'MONTH',
        year: 'YEAR',
        monthlySubscription: 'Monthly Subscription',
        yearlySubscription: 'Subscription for a year',
        tariffPlan: 'tariff plan',
        startWorkingRightNow: 'Start Working Now!',
        saving: 'Saving',
        bayingYearlySubscription: 'if you buy a one year subscription',
        toPayMonthlyForYear: 'one year with monthly payment',
        toPay: 'to Pay',
        forMonth: 'per month',
        forYear: 'per year',
        buttonText: 'BUY',
      },
    },
    contactUs: {
      headingText: 'Email us',
      leadText: `How can we help you?
         Describe your situation in detail
         in the form below and well get back to you
         shortly!`,
      formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
      nameEntryPlaceholder: 'Name',
      emailEntryPlaceholder: 'E-mail',
      messageEntryPlaceholder: 'Your message',
      submitFormButtonText: 'Send message',
      alerts: {
        feedbackSentHeading: 'Feedback was successfully sent!',
      },
    },
    apiIntegrationRequest: {
      headingText: 'Interested in API integration?',
      leadText: `Email us and well be sure to get back to you
         in the near future!`,
      formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
      nameEntryPlaceholder: 'Name',
      emailEntryPlaceholder: 'E-mail',
      messageEntryPlaceholder: 'Your message',
      submitFormButtonText: 'Send message',
      alerts: {
        apiIntegrationRequestSentHeading: 'API integration request was successfully sent!',
      },
    },
    auth: {
      login: {
        headingText: 'Welcome back!',
        leadText: 'Sign in to get started',
        formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
        emailEntryPlaceholder: 'E-mail',
        passwordEntryPlaceholder: 'Password',
        submitFormButtonText: 'Login',
        forgotPassword: 'Forgot your password?',
        register: 'Register',
      },
      registration: {
        general: {
          headingText: 'Weve been waiting for you!',
          leadText: 'Register to get started',
          formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
          emailEntryPlaceholder: 'E-mail',
          passwordEntryPlaceholder: 'Password',
          passwordConfirmationEntryPlaceholder: 'Reset Password',
          submitFormButtonText: 'Registration',
          licenseAgreement: 'By registering, you agree with',
          termsOfService: 'Ai Disraeli s Terms of Service',
          conjunctionAnd: 'and',
          privacyPolicy: 'Privacy Policy',
          alreadyHaveAnAccountThenLogin: 'Already have an account? Log in',
        },
        resendMail: {
          headingText: 'E-mail successfully sent!',
          leadText:
            'A confirmation email has been sent to you, follow the link in the email to complete your registration!',
          letterNotComing: 'No e-mail coming?',
          weCanResendItAgain: 'We can resend it',
          sent: 'Sent!',
          goToFeedbackButtonText: 'Contact support',
        },
        enterEmail: {
          headingText: 'Re-enter e-mail again',
          emailEntryPlaceholder: 'E-mail',
          submitFormButtonText: 'Continue',
        },
        confirmEmail: {
          sendingMail: 'Sending an e-mail to your mailbox...',
        },
      },
      passwordReset: {
        general: {
          headingText: 'Reset password',
          leadText: 'Enter the email you entered when you registered',
          formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
          emailEntryPlaceholder: 'Email',
          submitFormButtonText: 'Send email to reset password',
          enter: 'Login',
          register: 'Register',
        },
        confirmPasswordReset: {
          headingText: 'Create of a new password',
          leadText: 'Enter a new password',
          formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
          passwordEntryPlaceholder: 'New password',
          passwordConfirmationEntryPlaceholder: 'Reissue password',
          submitFormButtonText: 'Change password',
          alerts: {
            ['Password has been changed successfully!']: 'Password has been changed successfully',
          },
        },
        resendMail: {
          headingText: 'Email has been successfully sent!',
          leadText:
            'A confirmation email has been sent to you, follow the link in the email to complete the password change!',
          letterNotComing: 'No email coming?',
          weCanResendItAgain: 'We can resend it',
          sent: 'Sent!',
          goToFeedbackButtonText: 'Contact support',
        },
        enterEmail: {
          headingText: 'Enter email again',
          formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
          emailEntryPlaceholder: 'Email',
          submitFormButtonText: 'Continue',
        },
      },
    },
    workspaces: {
      primary: "You don't have workspaces yet!",
      secondary: 'Start creating text is seconds!',
      createFirstWorkspaceBtnText: 'Create first workspace',
      workspaceTypes: {
        personal: 'Personal',
        team: 'Team',
      },
      createNewWorkspaceBtnText: 'Create new workspace',
      enter: 'Enter',
    },
    workspaceModify: {
      workspaceCreation: 'Personal workspace creation',
      workspaceUpdate: 'Workspace settings',
      formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
      workspaceNameInputLabel: 'Workspace name',
      workspaceNameInputPlaceholder: 'Name',
      owner: 'Owner',
      creationDateLabel: 'Your workspace wos created:',
      createButtonText: 'Create workspace',
      updateButtonText: 'Save',
      rename: 'Rename',
      delete: 'Delete',
      alerts: {
        workspaceUpdated: 'The workspace has been updated successfully!',
        workspaceDeleted: 'The workspace has been deleted!',
      },
    },
    projects: {
      backToWorkspaces: 'Back to workspaces',
      createProjectBlock: {
        primary: 'Start word right now!',
        secondary: 'Generate unique texts in seconds',
        actionButtonText: 'Create new project',
      },
      tariffBlock: {
        heading: 'Overall balance state: ',
        creditHint: '1 credit = 1 text generation',
        antiPlagiarismCheckHint: 'Automatic text uniqueness check',
        creditsLeftNumeralDependentForms: {
          language: SITE_LANG_OPTIONS.EN,
          wordForms: 'credit left;credits left',
        },
        personalProjectsNumeralDependentForms: {
          language: SITE_LANG_OPTIONS.EN,
          wordForms: 'personal project;personal projects',
        },
        antiPlagiarismChecksNumeralDependentForms: {
          language: SITE_LANG_OPTIONS.EN,
          wordForms: 'anti-plagiarism check;anti-plagiarism checks',
        },
        willBeUpdated: 'updates',
        refill: 'Refill',
      },
      settings: 'Settings',
      delete: 'Delete',
      projects: 'Projects',
      description: 'DESCRIPTION',
    },
    projectModify: {
      projectCreation: 'Project creation',
      projectUpdate: 'Project settings',
      formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
      projectNameInputLabel: 'Project name',
      projectNameInputPlaceholder: 'Name',
      projectDescriptionInputLabel: 'Project description',
      projectDescriptionInputPlaceholder: 'A few words about project',
      inputLanguageDropdownLabel: 'Input language (source text)',
      outputLanguageDropdownLabel: 'Generation language (result)',
      createButtonText: 'Create project',
      updateButtonText: 'Save changes',
      alerts: {
        projectCreated: 'The project has been created!',
        projectUpdated: 'The project has been updated successfully!',
        projectDeleted: 'The project has been deleted!',
      },
    },
    profile: {
      heading: 'Profile settings',
      logout: 'Log out',
      planLabelText: 'Plan',
      upgrade: 'Upgrade',
      profileOwnerLabel: 'Profile owner',
      firstNameInputPlaceholder: 'Name',
      lastNameInputPlaceholder: 'Surname',
      saveChangesButtonText: 'Save changes',
      passwordChangeLabel: 'Password change',
      formRequiredFieldsNotification: 'Fields marked with an asterisk (*) are required.',
      oldPasswordInputPlaceholder: 'Old password',
      newPasswordInputPlaceholder: 'New password',
      passwordConfirmationInputPlaceholder: 'Repeat password',
      changePasswordButtonText: 'Change password',
      alerts: {
        passwordUpdatedSuccessfully: 'The password has been updated successfully!',
      },
    },
    generation: {
      backToProjects: 'Back to projects',
      rewrite: 'Rewrite',
      minimizeToTheCore: 'Text meaning',
      copyright: 'Copywriting',
      generatorDescription: 'The program will create a unique text on a given topic',
      generateText: 'Generate text',
      yourText: 'Your text',
      chooseTextTone: 'Choose the emotional coloring of the text',
      textChooseSubHeader: 'Choose the most appropriate from the list',
      generationSymbolsCount: 'Characters',
      generationSymbolsCountSubheader: 'The program will shorten a text to about 200 characters',
      copy: 'Copy',
      save: 'Save',
      moreSimilar: 'More similar',
      delete: 'Delete',
      antiPlagiarism: 'Anti-plagiarism',
      processingHeading: 'The text is magically creating!',
      processingText: 'Our artificial intelligence will take a little time...',
      autoSymbolsCountCalculate: 'Auto symbols count calculate',
    },
    errors: {
      ['err401']: 'Authorization required',
      ['err403']: 'Access denied',
      ['err404']: 'The requested resource was not found',
      ['err500']: 'Internal server error',
      ['err502']: 'Proxy error, gateway unreachable',

      ['This field may not be blank.']: 'This field may not be blank.',
      ['Enter a valid email address.']: 'Enter a valid email address.',
      ['The two password fields didn’t match.']: 'Passwords do not match.',
      ['This password is too short. It must contain at least 8 characters.']:
        'This password is too short. It must contain at least 8 characters.',
      ['Unable to log in with provided credentials.']:
        'Unable to log in with provided credentials.',
      ['Signature for tariff']: 'Signature for tariff',
      ['is missing from server']: 'is missing from server',
      ['Network error']: 'Network error',
      ['E-mail is not verified.']: 'E-mail is not verified',
      ['Workspaces limit reached for specified user']:
        'Workspaces limit reached for specified user',
      ['A user is already registered with this e-mail address']:
        'A user is already registered with this e-mail address',
      ['Ensure this field has no more than 256 characters.']:
        'Ensure this field has no more than 256 characters',
      ["Couldn't find an instance with specified id"]:
        "Couldn't find an instance with specified id",
      ['Projects limit reached for specified user']: 'Project creation limit exceeded!',
      ['Transactions modification is restricted']: 'Transactions modification is restricted',
      ['Your old password was entered incorrectly. Please enter it again.']:
        'Your old password was entered incorrectly. Please enter it again.',
      ['Ensure this field has no more than 254 characters.']:
        'Ensure this field has no more than 254 characters',
    },
    globalModals: {
      errorModalDefaultHeading: 'Error',
      errorModalButtonLabel: 'OK',
      infoModalButtonLabel: 'OK',
    },
  },
};
