export default {};

// import {SITE_LANG_OPTIONS} from '../store/appGlobal/types';
//
// export const RU = {
//   translation: {
//     mainHeader: {
//       upgradeTariffToPro: 'Улучшить до Pro',
//       proTariff: 'Тариф Pro',
//       teamsTariff: 'Тариф Teams',
//     },
//     landing: {
//       header: {
//         main: 'Главная',
//         tariffs: 'Тарифы',
//         contactUs: 'Связаться',
//         blog: 'Блог',
//         login: 'Войти',
//         registration: 'Регистрация',
//         profile: 'Личный кабинет',
//       },
//       main: {
//         heading: 'Искусственный интеллект,\nкоторый пишет любые\nтексты за вас',
//         contentText:
//           'Создавайте качественные тексты в блогах, статьи\nдля SEO, новости, пресс-релизы и многое другое\nза считанные секунды',
//         try4FreeButtonTitle: 'Попробовать бесплатно',
//         contentSecondaryText: 'Почти 100,000 авторов\nиспользуют Ai Disraeli',
//       },
//       whatCanBeCreatedBlock: {
//         headingText: 'Что вы можете создать\nс помощью AI DISRAELI?',
//         gridTile1HeadingText: 'Рекламные предложения',
//         gridTile1ListItemText1: 'Facebook Ads',
//         gridTile1ListItemText2: 'Google Ads',
//         gridTile1ListItemText3: 'Linkedin Ads',
//         gridTile2HeadingText: 'Контент\nдля социальных сетей',
//         gridTile2ListItemText1: 'Заголовки',
//         gridTile2ListItemText2: 'Посты в инстаграм',
//         gridTile2ListItemText3: 'Посты в социальные сети',
//         gridTile3HeadingText: 'Текстовое наполнение\nдля сайта',
//         gridTile3ListItemText1: 'SEO статьи',
//         gridTile3ListItemText2: 'Подзаголовки',
//         gridTile3ListItemText3: 'Мета-Описания',
//         gridTile4HeadingText: 'Коммерческие\nтексты',
//         gridTile4ListItemText1: 'Описания продуктов',
//         gridTile4ListItemText2: 'Преимущества продукта',
//         gridTile4ListItemText3: 'Микрокопии',
//         gridTile5HeadingText: 'Контент\nдля блогов',
//         gridTile5ListItemText1: 'Заголовки, идеи, наброски блогов',
//         gridTile5ListItemText2: 'Интро для блога',
//         gridTile5ListItemText3: 'Статьи для блога',
//         gridTile6HeadingText: 'Продающие\nтексты',
//         gridTile6ListItemText1: 'Продающий текст',
//         gridTile6ListItemText2: 'Придание маркетингового оттенка',
//         gridTile6ListItemText3: 'Тексты по принципам АИДА',
//       },
//       howItWorks: {
//         heading: 'Как это работает?',
//         lead: 'AI Disraeli позволяет с помощью искусственного интеллекта\nснизить затраты на копирайтинг и увеличить скорость\nнаписания и количество текстов',
//         step1: 'Выберите тип генерации',
//         step2: 'Введите базовую информацию для генерации',
//         step3: 'Получите свои результаты и отредактируйте, если это необходимо',
//         whatCanHeading: 'Что умеет делать\nAI DISRAELI?',
//         whatCan1: 'Переписать текст — новый текст с сохранением смысла',
//         whatCan2: 'Сокращение текста до сути',
//         whatCan3: 'Написать текст по заданной теме',
//         whatCan4: 'Создать текст с необходимым эмоциональным оттенком',
//         whatCanAdditional: '10 вариантов текста при каждой генерации!',
//       },
//       footer: {
//         main: 'Главная',
//         tariffs: 'Тарифы',
//         contactUs: 'Связаться',
//         blog: 'Блог',
//         profile: 'Личный кабинет',
//         privacyPolicy: 'Политика конфиденциальности',
//         allRightsAreProtected: 'Все права защищены',
//       },
//       targetAudience: {
//         heading: 'Для кого подойдет AI DISRAELI?',
//         copywritersCardHeader: 'Копирайтеры',
//         copywritersCardText:
//           'Пишите уникальные статьи всего одним щелчком мыши, используя инструменты искусственного интеллекта для копирайтинга',
//         studentsCardHeader: 'Студенты',
//         studentsCardText:
//           'Создавайте оригинальные студенческие работы и высококачественные эссе за считанные секунды',
//         SEOCardHeader: 'SEO-специалисты',
//         SEOCardText:
//           'Аглоритм для SEO-статей может создавать контент подлинного человеческого качества, удовлетворяющий поисковые системы',
//         journalistsCardHeader: 'Журналисты',
//         journalistsCardText:
//           'Произведите впечатление на своих читателей и автоматически создайте первый набросок своей истории',
//         bloggersCardHeader: 'Блоггеры',
//         bloggersCardText:
//           'Ваш персональный генератор сообщений в блоге с искусственным интеллектом создаёт идеальный контент для любой ниши',
//         marketersCardHeader: 'Маркетологи',
//         marketersCardText:
//           'Автоматизируйте свои задачи по маркетингу контента с помощью программного обеспечения AI для копирайтера',
//         onlineShopsCardHeader: 'Интернет-магазины',
//         onlineShopsCardText:
//           'Создавайте различные варианты текстов для ваших рекламных предложений и генерируйте уникальные статьи для тестирования сайта',
//         devsCardHeader: 'Разработчики',
//         devsCardText:
//           'Получите свой собственный инструмент на основе искусственного интеллекта и создавайте контент в 10 раз быстрее',
//         tryForFreeButtonText: 'попробовать бесплатно',
//       },
//     },
//     blog: {
//       pageHeadingText: 'Блог',
//       viewsNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'просмотр;просмотра;просмотров',
//       },
//       continueReadingButtonText: 'Читать далее',
//     },
//     tariffs: {
//       heading: 'Тарифы',
//       lead: 'Экономьте до 15%, выбирая один из наших годовых планов',
//       monthly: 'ЕЖЕМЕСЯЧНЫЕ',
//       yearly: 'ЕЖЕГОДНЫЕ',
//       personal: 'Персональные',
//       forBusiness: 'Для бизнеса',
//       forFree: 'Бесплатно',
//       perMonth: 'месяц',
//       perYear: 'месяц при оплате за год',
//       atMonth: 'в месяц',
//       atFirstMonth: 'в первый месяц',
//       antiPlagiarism: 'Антиплагиат',
//       perGeneration: 'за генерацию',
//       tryForFree: 'Попробовать',
//       selectPlan: 'Выбрать план',
//       requestPrice: 'Оставить заявку',
//       introTariffDescription: 'Идеально для ознакомления с сервисом',
//       liteTariffDescription: 'Для тех, у кого мало задач',
//       starterTariffDescription: 'Для тех, кто только планирует начать',
//       proTariffDescription: 'Для профессионалов, которые ценят свое время',
//       teamTariffDescription: 'Для команд, которые ценят совместную работу',
//       apiTariffDescription: 'Для предприятий, желающих встроить функционал в свои продукты',
//       popularLabel: 'Популярный',
//       unlimitedAntiPlagiarism: 'Безлим. Антиплагиат',
//       unlimitedProjects: 'Безлим. проекты',
//       unlimitedWorkspaces: 'Безлим. пространства',
//       collaborateOnFilesAndProjects: 'Совместная работа над файлами и проектами',
//       individualCPA: 'Индивидуальный CPA',
//       personalAPI: 'Персональный API',
//       creditsPerMonthNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'кредит;кредита;кредитов',
//       },
//       languagesNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'язык;языка;языков',
//       },
//       initialBonusCreditsNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'бонусный кредит;бонусных кредита;бонусных кредитов',
//       },
//       antiPlagiarismChecksNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'проверка;проверки;проверок',
//       },
//       maxProjectsNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'проект;проекта;проектов',
//       },
//       maxWorkspacesNumeralDependentForms: {
//         language: SITE_LANG_OPTIONS.RU,
//         wordForms: 'рабочее пространство;рабочих пространства;рабочих пространств',
//       },
//       modal: {
//         month: 'МЕСЯЦ',
//         year: 'ГОД',
//         monthlySubscription: 'Подписка на месяц',
//         yearlySubscription: 'Подписка на год',
//         tariffPlan: 'тарифный план',
//         startWorkingRightNow: 'Начните работу прямо сейчас!',
//         saving: 'Экономия',
//         bayingYearlySubscription: 'при покупке подписки на год',
//         toPayMonthlyForYear: 'год при ежемесячной оплате',
//         toPay: 'к оплате',
//         forMonth: 'в месяц',
//         forYear: 'в год',
//         buttonText: 'КУПИТЬ',
//       },
//     },
//     contactUs: {
//       headingText: 'Напишите нам',
//       leadText: `Как мы можем помочь вам?
//          Опишите подробно свою ситуацию
//          в форме ниже и мы свяжемся с вами
//          в ближайшее время!`,
//       formRequiredFieldsNotification: 'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//       nameEntryPlaceholder: 'Имя',
//       emailEntryPlaceholder: 'Почта',
//       messageEntryPlaceholder: 'Ваше сообщение',
//       submitFormButtonText: 'Отправить сообщение',
//       alerts: {
//         feedbackSentHeading: 'Отзыв был успешно отправлен!',
//       },
//     },
//     apiIntegrationRequest: {
//       headingText: 'Заинтересованы в интеграции API?',
//       leadText: `Напиши нам и мы обязательно свяжемся
//          в ближайшее время!`,
//       formRequiredFieldsNotification: 'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//       nameEntryPlaceholder: 'Имя',
//       emailEntryPlaceholder: 'Почта',
//       messageEntryPlaceholder: 'Ваше сообщение',
//       submitFormButtonText: 'Отправить сообщение',
//       alerts: {
//         apiIntegrationRequestSentHeading: 'Запрос на интеграцию API был успешно отправлен!',
//       },
//     },
//     auth: {
//       login: {
//         headingText: 'С возвращением!',
//         leadText: 'Войдите, чтобы начать работу',
//         formRequiredFieldsNotification:
//           'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//         emailEntryPlaceholder: 'Email',
//         passwordEntryPlaceholder: 'Пароль',
//         submitFormButtonText: 'Войти',
//         forgotPassword: 'Забыли пароль?',
//         register: 'Регистрация',
//       },
//       registration: {
//         general: {
//           headingText: 'Мы ждали вас!',
//           leadText: 'Зарегистрируйтесь, чтобы начать работу',
//           formRequiredFieldsNotification:
//             'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//           emailEntryPlaceholder: 'Email',
//           passwordEntryPlaceholder: 'Пароль',
//           passwordConfirmationEntryPlaceholder: 'Повторите пароль',
//           submitFormButtonText: 'Регистрация',
//           licenseAgreement: 'Регистрируясь, вы соглашаетесь с',
//           termsOfService: 'Условиями предоставления услуг Ai Disraeli',
//           conjunctionAnd: 'и',
//           privacyPolicy: 'Политикой конфиденциальности',
//           alreadyHaveAnAccountThenLogin: 'Уже есть аккаунт? Войти',
//         },
//         resendMail: {
//           headingText: 'Письмо успешно отправлено!',
//           leadText:
//             'На вашу почту отправлено подтверждение, перейдите по ссылке в письме, чтобы завершить регистрацию!',
//           letterNotComing: 'Не приходит письмо?',
//           weCanResendItAgain: 'Мы можем отправить его повторно',
//           sent: 'Отправлено!',
//           goToFeedbackButtonText: 'Обратиться в поддержку',
//         },
//         enterEmail: {
//           headingText: 'Введите email повторно',
//           emailEntryPlaceholder: 'Email',
//           submitFormButtonText: 'Продолжить',
//         },
//         confirmEmail: {
//           sendingMail: 'Отправляем письмо вам на почту...',
//         },
//       },
//       passwordReset: {
//         general: {
//           headingText: 'Сбросить пароль',
//           leadText: 'Введите email, указанный при регистрации',
//           formRequiredFieldsNotification:
//             'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//           emailEntryPlaceholder: 'Email',
//           submitFormButtonText: 'Отправить письмо для сброса пароля',
//           enter: 'Войти',
//           register: 'Регистрация',
//         },
//         confirmPasswordReset: {
//           headingText: 'Придумайте новый пароль',
//           leadText: 'Введите новый пароль',
//           formRequiredFieldsNotification:
//             'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//           passwordEntryPlaceholder: 'Новый пароль',
//           passwordConfirmationEntryPlaceholder: 'Повторите пароль',
//           submitFormButtonText: 'Изменить пароль',
//           alerts: {
//             ['Password has been reset successfully!']: 'Пароль успешно изменён',
//           },
//         },
//         resendMail: {
//           headingText: 'Письмо успешно отправлено!',
//           leadText:
//             'На вашу почту отправлено подтверждение, перейдите по ссылке в письме, чтобы завершить смену пароля!',
//           letterNotComing: 'Не приходит письмо?',
//           weCanResendItAgain: 'Мы можем отправить его повторно',
//           sent: 'Отправлено!',
//           goToFeedbackButtonText: 'Обратиться в поддержку',
//         },
//         enterEmail: {
//           headingText: 'Введите email повторно',
//           formRequiredFieldsNotification:
//             'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//           emailEntryPlaceholder: 'Email',
//           submitFormButtonText: 'Продолжить',
//         },
//       },
//     },
//     workspaces: {
//       primary: 'У вас пока нет рабочих комнат!',
//       secondary: 'Начните создавать тексты за считанные секунды.',
//       createFirstWorkspaceBtnText: 'Создать первую комнату',
//       workspaceTypes: {
//         personal: 'Персональные',
//         team: 'Командные',
//       },
//       createNewWorkspaceBtnText: 'Создать новую комнату',
//       enter: 'Войти',
//     },
//     workspaceModify: {
//       workspaceCreation: 'Создание персональной комнаты',
//       workspaceUpdate: 'Настройки комнаты',
//       formRequiredFieldsNotification: 'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//       workspaceNameInputLabel: 'Название комнаты',
//       workspaceNameInputPlaceholder: 'Название',
//       owner: 'Владелец',
//       creationDateLabel: 'Ваша комната была создана:',
//       createButtonText: 'Создать комнату',
//       updateButtonText: 'Сохранить',
//       rename: 'Переименовать',
//       delete: 'Удалить',
//       alerts: {
//         workspaceUpdated: 'Комната была успешно изменена!',
//         workspaceDeleted: 'Комната была удалена!',
//       },
//     },
//     projects: {
//       backToWorkspaces: 'Вернуться в список комнат',
//       createProjectBlock: {
//         primary: 'Начните работу прямо сейчас!',
//         secondary: 'Генерируйте уникальные тексты за считанные секунды',
//         actionButtonText: 'Создать новый проект',
//       },
//       tariffBlock: {
//         heading: 'Общий статус тарифа: ',
//         creditHint: '1 кредит = 1 генерация текста',
//         antiPlagiarismCheckHint: 'Автоматическая проверка уникальности текста',
//         creditsLeftNumeralDependentForms: {
//           language: SITE_LANG_OPTIONS.RU,
//           wordForms: 'кредит остался;кредита осталось;кредитов осталось',
//         },
//         personalProjectsNumeralDependentForms: {
//           language: SITE_LANG_OPTIONS.RU,
//           wordForms: 'личный проект;личных проекта;личных проектов',
//         },
//         antiPlagiarismChecksNumeralDependentForms: {
//           language: SITE_LANG_OPTIONS.RU,
//           wordForms: 'проверка антиплагиат;проверки антиплагиат;проверок антиплагиат',
//         },
//         willBeUpdated: 'обновится',
//         refill: 'Пополнить',
//       },
//       settings: 'Настройки',
//       delete: 'Удалить',
//       projects: 'Проекты',
//       description: 'ОПИСАНИЕ',
//     },
//     projectModify: {
//       projectCreation: 'Создание проекта',
//       projectUpdate: 'Настройки проекта',
//       formRequiredFieldsNotification: 'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//       projectNameInputLabel: 'Название проекта',
//       projectNameInputPlaceholder: 'Название',
//       projectDescriptionInputLabel: 'Описание проекта',
//       projectDescriptionInputPlaceholder: 'Пару слов о проекте',
//       inputLanguageDropdownLabel: 'Язык ввода (исходный текст)',
//       outputLanguageDropdownLabel: 'Язык генерации (результат)',
//       createButtonText: 'Создать проект',
//       updateButtonText: 'Сохранить изменения',
//       alerts: {
//         projectCreated: 'Проект создан!',
//         projectUpdated: 'Проект был успешно изменен!',
//         projectDeleted: 'Проект удален!',
//       },
//     },
//     profile: {
//       heading: 'Настройки аккаунта',
//       logout: 'Выход',
//       planLabelText: 'Тарифный план',
//       upgrade: 'Улучшить',
//       profileOwnerLabel: 'Владелец аккаунта',
//       firstNameInputPlaceholder: 'Имя',
//       lastNameInputPlaceholder: 'Фамилия',
//       saveChangesButtonText: 'Сохранить изменения',
//       passwordChangeLabel: 'Смена пароля',
//       formRequiredFieldsNotification: 'Поля отмеченные звездочкой (*) обязательны для заполнения.',
//       oldPasswordInputPlaceholder: 'Старый пароль',
//       newPasswordInputPlaceholder: 'Новый пароль',
//       passwordConfirmationInputPlaceholder: 'Повторите пароль',
//       changePasswordButtonText: 'Сменить пароль',
//       alerts: {
//         passwordUpdatedSuccessfully: 'Пароль успешно изменен!',
//       },
//     },
//     generation: {
//       backToProjects: 'Вернуться в список проектов',
//       rewrite: 'Рерайт',
//       minimizeToTheCore: 'Сокращение до сути',
//       copyright: 'Копирайт',
//       generatorDescription: 'Программа создаст уникальный текст, на заданную тему.',
//       generateText: 'Сгенерировать текст',
//       yourText: 'Ваш текст',
//       chooseTextTone: 'Выберете эмоциональную окраску текста',
//       textChooseSubHeader: 'Выберите наиболее подходящее из списка',
//       generationSymbolsCount: 'Количество символов',
//       generationSymbolsCountSubheader: 'Программа сократит текст примерно до 200 символов',
//       copy: 'Копировать',
//       save: 'Сохранить',
//       moreSimilar: 'Больше похожих',
//       delete: 'Удалить',
//       antiPlagiarism: 'Антиплагиат',
//       processingHeading: 'Волшебным образом создается текст!',
//       processingText: 'Нашему искусственному интеллекту потребуется немного времени...',
//       autoSymbolsCountCalculate: 'Определить объем автоматически',
//     },
//     errors: {
//       ['err401']: 'Необходима авторизация',
//       ['err403']: 'Доступ запрещен',
//       ['err404']: 'Запрашиваемый ресурс не найден',
//       ['err500']: 'Внутренняя ошибка сервера',
//       ['err502']: 'Ошибка прокси сервера, шлюз недоступен',
//
//       ['This field may not be blank.']: 'Это поле не может быть пустым.',
//       ['Enter a valid email address.']: 'Введите валидный адрес электронной почты.',
//       ['The two password fields didn’t match.']: 'Пароли не совпадают.',
//       ['This password is too short. It must contain at least 8 characters.']:
//         'Этот пароль слишком короткий. Он должен включать как минимум 8 символов.',
//       ['Unable to log in with provided credentials.']:
//         'Невозможно войти с указанными учётными данными.',
//       ['E-mail is not verified.']: 'E-mail не подтвержден.',
//       ['Workspaces limit reached for specified user']: 'Превышен лимит создания комнат!',
//       ['Signature for tariff ']: '',
//       [' is missing from server']: '',
//       ['Network error']: 'Ошибка сети',
//       ['A user is already registered with this e-mail address']:
//         'Пользователь с таким e-mail адресом уже существует',
//       ['Ensure this field has no more than 256 characters.']:
//         'Убедитесь, что это поле содержит не больше 256 символов.',
//       ["Couldn't find an instance with specified id"]:
//         'Не удалось найти экземпляр с указанным идентификатором',
//       ['Projects limit reached for specified user']: 'Превышен лимит создания проектов!',
//       ['Transactions modification is restricted']: 'Модификация транзакций ограничена',
//       ['Your old password was entered incorrectly. Please enter it again.']:
//         'Ваш старый пароль был введён неправильно. Пожалуйста, введите его снова',
//       ['Ensure this field has no more than 254 characters.']:
//         'Убедитесь, что это поле содержит не больше 254 символов.',
//     },
//     globalModals: {
//       errorModalDefaultHeading: 'Ошибка',
//       errorModalButtonLabel: 'ОК',
//       infoModalButtonLabel: 'ОК',
//     },
//   },
// };
