# Generated by Django 4.0.1 on 2022-01-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price_monthly',
            new_name='monthly_price_for_month',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='price_yearly',
            new_name='monthly_price_for_year',
        ),
    ]
