# Generated by Django 4.0.1 on 2022-01-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_rename_price_monthly_plan_monthly_price_for_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_of_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
