# Generated by Django 4.0.1 on 2022-01-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_plan_price_of_additional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price_of_additional',
            new_name='price_of_additional_for_month',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_of_additional_for_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
