# Generated by Django 4.0.1 on 2022-01-31 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_rename_price_of_additional_plan_price_of_additional_for_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
