# Generated by Django 4.0.1 on 2022-02-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
