# Generated by Django 4.0.1 on 2022-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_remove_personalbalance_id_alter_personalbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbalance',
            name='antiplagiarism_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalbalance',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalbalance',
            name='projects_additional',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalbalance',
            name='rooms_additional',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
