# Generated by Django 4.0.1 on 2022-02-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_alter_personalbalance_antiplagiarism_checks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('source_lang', models.CharField(max_length=2)),
                ('target_lang', models.CharField(max_length=2)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api_app.personalworkspace')),
            ],
        ),
        migrations.RenameField(
            model_name='personalbalance',
            old_name='rooms_additional',
            new_name='workspaces_additional',
        ),
        migrations.RenameField(
            model_name='personalbalancetransaction',
            old_name='rooms_additional',
            new_name='workspaces_additional',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
